
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndzhonpzauwwwffggmdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kemhvbnB6YXV3d3dmZmdnbWR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NzU3OTksImV4cCI6MjA1OTM1MTc5OX0.JEvJllMafcU79hpK_dizCb96oQ05rOaSDwxZxQN13JU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
